### ISSUE TITLE
Bib and citations

### ISSUE THREAD

**Issue by yabellini** [ropensci-review-tools/babeldown#49]
The package is translating citations (example: https://github.com/ropensci-review-tools/translation_guide/pull/37/files, starting in line 19).  We shouldn't translate the bibliography and the citations.

**Comment by maelle** [comment]
I wonder how we could handle this since footnotes should generally be translated. Would it make sense to protect the citations, that is to say, the user would have to wrap the citations in something to tell babeldown not to touch them.

**Comment by maelle** [comment]
@yabellini why don't you use actual citations? https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-citations that'd be easier to protect as it'd be specific to citations.

I am inspired by https://github.com/r-lib/hugodown#citations

**Comment by maelle** [comment]
I'm going to work on square brackets protection, also useful for footnotes

**Comment by yabellini** [comment]
> @yabellini why don't you use actual citations? https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-citations that'd be easier to protect as it'd be specific to citations.
> 
> I am inspired by https://github.com/r-lib/hugodown#citations

Yes, of course.  I'm using this format for the T3 book. The bib is on the bib file and we reference it using the @ and the name. I can change that and add it to the guidelines.
