### ISSUE TITLE
Fail to implement deepl_update()

### ISSUE THREAD

**Issue by ntluong95** [ropensci-review-tools/babeldown#57]
I have a Quarto book that is available in English.
Then I was successfully create a German (DE) version of it by using `deepl_translate_quarto()` function

Next I want to try making changes in English version, and using  `deepl_update()` function to implement on DE version and other languages (ideally there are currently 7 language versions available, but they were translated manually)

For example, I made changes on "basics.qmd", "factors.qmd" chapters, so I wrote this function to implement changes
```r
chapter_changes = c("basics.qmd", "factors.qmd")
chapter_changes_update = c("basics.de.qmd", "factors.de.qmd")


for (i in 1:length(chapter_changes)) {
        babeldown::deepl_update(
                path = here::here("new_pages", chapter_changes[i]),
                out_path = here::here("new_pages", chapter_changes_update[i]),
                source_lang = "EN",
                target_lang = "DE",
                formality = "less",
                yaml_fields = NULL)
}
```
but I got this error: Error in log[["commit"]][[latest_source_commit_index]] : 
  subscript out of bounds

The steps I did was first made changes on EN version, commit to Git, and run the above function
In addition, I have also the following questions:

- Will the update be only in markdown text, or applied also to code chunk?
- If we add or delete code chunks, will this be also updated in other languages? I guess no?

**Comment by maelle** [comment]
adding this link in case you didn't know it https://ropensci.org/blog/2024/01/16/deepl-update-babeldown/

**Comment by maelle** [comment]
see #58

**Comment by maelle** [comment]
@ntluong95 could you please install babeldown (`pak::pak("ropensci-review-tools/babeldown")`) and try running your code again?

**Comment by maelle** [comment]
I opened the issue as I don't want to close it before you confirm it's fixed. :innocent:

**Comment by ntluong95** [comment]
Hi it is fixed 🎉🎉
But I did not see changes in the code chunk, only markdown text has been updated

**Comment by maelle** [comment]
Ok, see #59
