### ISSUE TITLE
Examine babel_update() behavior reg code chunks

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/babeldown#59]
cc @ntluong95

**Comment by ntluong95** [comment]
Very promising. Look fw to it

**Comment by maelle** [comment]
@ntluong95 I don't see what is wrong with deepl_update() behavior now, could you please share a reprex?

In https://github.com/maelle/updatechunks/pull/1 

- the first commit updates an English file by changing text but also the content of two code chunks, and adding a code chunk.
- the second commit uses deepl_update(). the text has been translated, and the chunk changes are present too so all is well?


now, what might be problematic is if the code chunks are translated by users, as I fear the translations might get lost, but that was not your problem?

**Comment by maelle** [comment]
Can we close this or is further work/help needed @ntluong95 ?

**Comment by ntluong95** [comment]
Hi Maelle,

Thank you for your supports. So far the function works well. We can close it for now
