### ISSUE TITLE
crossreferences can be translated or not

### ISSUE THREAD

**Issue by xtimbeau** [ropensci-review-tools/babeldown#64]
Sometimes cross ref are translated, sometimes not.

```qmd
---
title: "crossref"
description: "comment protéger les références croisées dans quarto et babeldown ?"
---

Imaginons une référence croisée à un chapitre qui suit. 

La référence n'est pas protégée quand elle est mise @sec-chapitre ou sous la forme [@sec-chapitre],
mais @sec-chapitre2 est protégée.

## Le chapitre suivant {#sec-chapitre}

## un autre chapitre {#sec-chapitre2}
```

is translated from french to english as (note the @sec-chapter):

```qmd
---
title: crossref
description: how do you protect cross-references in quarto and babeldown?
---

Let's imagine a cross-reference to a chapter that follows.

The reference is not protected when it is put in @sec-chapter or in the form [@sec-chapter],
but @sec-chapitre2 is protected.

## The next chapter {#sec-chapitre}

## another chapter {#sec-chapitre2}
``` 

A way is to add some number to all cross-refs, but I think there is another solution ?

**Comment by maelle** [comment]
Right, they should never get translated automatically, I'll have to explore.

**Comment by maelle** [comment]
Related: #49

**Comment by maelle** [comment]
oh I found the bug! In `protect_squaries()` I did not account for the possibility of hyphens!

Thanks so much for your contributions & patience @xtimbeau, this is really making the package better. :pray:

**Comment by xtimbeau** [comment]
thanks to you!

Le ven. 5 avr. 2024 à 11:59, Maëlle Salmon ***@***.***> a
écrit :
