### ISSUE TITLE
Translation quality when using non semantic line breaks

### ISSUE THREAD

**Issue by yabellini** [ropensci-review-tools/babeldown#74]
We see that the quality of the translation is not so good when there are nonsemantic line breaks in the original text, breaking the text in weird ways. 
Something to think about is whether or not Babeldown should try to handle this situation.

**Comment by maelle** [comment]
But Yani no one should ever use non semantic line breaks :joy: Just kidding.

Do you have any example at hand? 

Maybe babeldown could squish the input by sentence but if users had been doing something else semantic like adding line breaks after sentences but also after commas, we'd be breaking their nice system. :thinking: 

Maybe it's a docs issue, and babeldown should promote semantic line breaks?

What we have in the docs now: https://github.com/ropensci-review-tools/babeldown?tab=readme-ov-file#line-wrapping

**Comment by maelle** [comment]
babeldown docs could refer to https://github.com/ropenscilabs/aeolus
